apps/blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^archive/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchiveView.as_view(), name='archive'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
]

apps/comment/urls.py
from django.conf.urls import url

from . import views

app_name = 'comment'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.comment, name='comment'),
]

blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from apps.blog.feeds import AllPostsRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('apps.blog.urls')),
    url(r'', include('apps.comment.urls')),

    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
]

apps/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from django.utils.html import strip_tags
from django.utils.text import slugify
from django.utils.functional import cached_property

import markdown
from markdown.extensions.toc import TocExtension

# Create your models here.


def generate_rich_content(value):
    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify),
        ]
    )
    content = md.convert(value)
    toc = md.toc
    return {'content': content, 'toc': toc}


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='分类名')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    
    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=50, verbose_name='标签名')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    
    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=100, verbose_name='标题')
    body = models.TextField(verbose_name='正文')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    excerpt = models.CharField(max_length=200, blank=True, verbose_name='摘要')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='分类')
    tags = models.ManyToManyField(Tag, blank=True, verbose_name='标签')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='作者')
    view = models.PositiveIntegerField(default=0, editable=False, verbose_name='阅读')

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name
        ordering = ["-created_time"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        md = markdown.Markdown(extensions=(
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ))

        self.excerpt = strip_tags(md.convert(self.body))[:54]
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_view(self):
        self.view += 1
        self.save(update_fields=['view'])

    @property
    def toc(self):
        return self.rich_content.get('toc', '')

    @property
    def body_html(self):
        return self.rich_content.get('content', '')

    @cached_property
    def rich_content(self):
        return generate_rich_content(self.body)

apps/comment/models.py
from django.db import models
from django.contrib.auth.models import User

from apps.blog.models import Post

# Create your models here.


class Comment(models.Model):
    text = models.TextField(verbose_name='内容')
    author = models.ForeignKey(User, verbose_name='作者')
    post = models.ForeignKey(Post, verbose_name='文章', on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']

    def __str__(self):
        return f'{self.author}: {self.text[:20]}'

apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    username = models.CharField(max_length=50, verbose_name='用户名')
    nikename = models.CharField(max_length=50, verbose_name='昵称')
    email = models.EmailField(verbose_name='邮箱')
    password = models.CharField(max_length='50', verbose_name='密码')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    class Meta:
        verbose_name = '用户'

    def __str__(self):
        return self.username
    

apps/comment/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'url', 'text']

apps/blog/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.db.models import Q
from django.utils.text import slugify

from pure_pagination.mixins import PaginationMixin
import markdown
from markdown.extensions.toc import TocExtension

from .models import Category, Tag, Post

# Create your views here.


class IndexView(PaginationMixin, ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 10


class SearchView(IndexView):
    def get_context_data(self):
        context = super().get_context_data()
        context.update({
            'q': self.request.GET.get('q', '')
        })
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        q = self.request.GET.get('q')
        if not q:
            return queryset
        return queryset.filter(Q(title__icontains=q) | Q(body__icontains=q))


class ArchiveView(IndexView):
    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return (
            super().get_queryset().filter(created_time__year=year, created_time__month=month)
        )


class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super().get_queryset().filter(category=cate)


class TagView(IndexView):
    def get_queryset(self):
        t = get_object_or_404(Tag, pk=self.kwargs.get("pk"))
        return super().get_queryset().filter(tags=t)


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        self.object.increase_view()
        return response

apps/comment/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views.decorators.http import require_POST

from .forms import CommentForm
from apps.blog.models import Post

# Create your views here.


@require_POST
def comment(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
        messages.add_message(request, messages.SUCCESS, '评论发表成功！', extra_tags='success')
        return redirect(post)

    context = {
        'post': post,
        'form': form,
    }
    messages.add_message(request, messages.ERROR, '评论发表失败！请修改表单中的错误后重新提交。', extra_tags='danger')
    return render(request, 'comment/preview.html', context=context)

apps/user/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
{% load bootstrap3 %}
{% load blog_extras %}


<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    {% bootstrap_css %}
    <link href="https://cdn.bootcdn.net/ajax/libs/ionicons/2.0.1/css/ionicons.min.css", rel="stylesheet">
    <link href="https://cdn.bootcdn.net/ajax/libs/highlight.js/9.18.3/styles/github.min.css" rel="stylesheet">
    <link href="{% static 'css/pace.css' %}", rel="stylesheet">
    <link href="{% static 'css/custom.css' %}", rel="stylesheet">

    <!-- js -->
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <script src="{% static 'jquery/jquery.js' %}"></script>
    <script src="{% static 'jquery/plugins/jquery.cookie.js' %}"></script>
    <script src="{% static 'jquery/plugins/jquery.utils.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>

    <style>
        .codehilite {
            padding: 0;
        }

        /* for block of numbers */
        .hljs-ln-numbers {
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -khtml-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;

            text-align: center;
            color: #ccc;
            border-right: 1px solid #CCC;
            vertical-align: top;
            padding-right: 5px;
        }

        .hljs-ln-n {
            width: 30px;
        }

        /* for block of code */
        .hljs-ln .hljs-ln-code {
            padding-left: 10px;
            white-space: pre;
        }
    </style>
</head>

{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <spanaria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
    {% endfor %}
{% endif %}

<body>
    <div class="container">
        <header id="site-header">
            <div class="row">
                <div class="col-md-4 col-sm-5 col-xs-8">
                    <div class="logo">
                        <h1><a href="{% url 'blog:index' %}"><b>Black</b> &amp; White</a></h1>
                    </div>
                </div><!-- col-md-4 -->
                <div class="col-md-8 col-sm-7 col-xs-4">
                    <nav class="main-nav" role="navigation">
                        <div class="navbar-header">
                            <button type="button" id="trigger-overlay" class="navbar-toggle">
                                <span class="ion-navicon"></span>
                            </button>
                        </div>
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                                <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                                <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                                <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                            </ul>
                        </div><!-- /.navbar-collapse -->
                    </nav>
                    <div id="header-search-box">
                        <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                        <div id="search-form" class="search-form">
                            <form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">
                                <input type="search" name='q' placeholder="搜索" value={{ q }}>
                                <button type="submit"><span class="ion-ios-search-strong"></span></button>
                            </form>
                        </div>
                    </div>
                </div><!-- col-md-8 -->
            </div>
        </header>
    </div>
    <div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
    <div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-8">
                {% block main %}
                {% endblock main %}
                </main>
                <aside class="col-md-4">
                    {% block toc %}
                    {% endblock toc %}

                    {% show_recent_post %}
                    {% show_archive %}
                    {% show_categorie %}
                    {% show_tag %}

                    <div class="rss">
                        <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                    </div>
                </aside>
            </div>
        </div>
    </div>
    <footer id="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p class="copyright">
                        &copy 2017 - 采集自<a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a>
                        - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                    </p>
                </div>
            </div>
        </div>
    </footer>

    <!-- Mobile Menu -->
    <div class="overlay overlay-hugeinc">
        <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
        <nav>
            <ul>
                <li><a href="{% url 'blog:index' %}">首页</a></li>
                <li><a href="full-width.html">博客</a></li>
                <li><a href="about.html">关于</a></li>
                <li><a href="contact.html">联系</a></li>
            </ul>
        </nav>
    </div>

    <script src="{% static 'js/script.js' %}"></script>
    <body>
        <script src="https://cdn.bootcdn.net/ajax/libs/highlight.js/9.18.3/styles/github.min.css"></script>
        <script src="https://cdn.bootcdn.net/ajax/libs/highlightjs-line-numbers.js/2.8.0/highlightjs-line-numbers.min.js"></script>
        <script>
            hljs.initHighlightingOnLoad();
            hljs.initLineNumbersOnLoad();
        </script>
    </body>
</body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}
{% load comment_extras %}

{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="#comment-area">{{ post.comment_set.count }} 评论</a></span>
                <span class="view-count"><a href="#">{{ post.view }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body_html|safe }}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
            {% show_comment_form post %}
        <div class="comment-list-panel">
            {% show_comment post %}
        </div>
    </section>
{% endblock main %}

{% block toc %}
    {% if post.toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        <div class="toc">
            <ul>
            {{ post.toc|safe }}
            </ul>
        </div>
    </div>
    {% endif %}
{% endblock toc %}

templates/blog/inclusions/_archive.html
<div class="widget widget-archives">
    <h3 class="widget-title">归档</h3>
    <ul>
        {% for date in date_list %}
        <li>
            <a href="{% url 'blog:archive' date.year date.month %}">
                {{ date.year }} 年 {{ date.month }} 月
            </a>
        </li>
        {% empty %}
        暂无归档！
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_categorie.html
<div class="widget widget-category">
    <h3 class="widget-title">分类</h3>
    <ul>
        {% for category in category_list %}
        <li>
            <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span class="post-count">({{ category.num_posts }})</span></a>
        </li>
        {% empty %}
        暂无分类！
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_recent_post.html
<div class="widget widget-recent-posts">
    <h3 class="widget-title">最新文章</h3>
    <ul>
        {% for post in recent_post_list %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
        {% empty %}
        暂无文章！
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_tag.html
<div class="widget widget-tag-cloud">
    <h3 class="widget-title">标签云</h3>
    <ul>
        {% for tag in tag_list %}
        <li>
            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }} <span class="post-count">({{ tag.num_posts }})</a>
        </li>
        {% empty %}
        暂无标签！
        {% endfor %}
    </ul>
</div>

templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
    {% if error_msg %}
    <p>{{ error_msg }}</p>
    {% endif %}

    {% for post in post_list %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a></span>
                <span class="view-count"><a href="{{ post.get_absolute_url }}">{{ post.view }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            <p>{{ post.excerpt }}...</p>
            <div class="read-more cl-effect-14">
                <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
            </div>
        </div>
    </article>
    {% empty %}
    <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}
    {% if is_paginated %}
        {{ page_obj.render }}
    {% endif %}
{% endblock main %}

templates/comment/inclusions/_form.html
<form action="{% url 'comment:comment' post.pk %}" method="post" class="comment-form">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-4">
            <label for="{{ form.name.id_for_label }}">{{ form.name.label }}：</label>
            {{ form.name }}
            {{ form.name.errors }}
        </div>
        <div class="col-md-4">
            <label for="{{ form.email.id_for_label }}">{{ form.email.label }}：</label>
            {{ form.email }}
            {{ form.email.errors }}
        </div>
        <div class="col-md-4">
            <label for="{{ form.url.id_for_label }}">{{ form.url.label }}：</label>
            {{ form.url }}
            {{ form.url.errors }}
        </div>
        <div class="col-md-12">
            <label for="{{ form.text.id_for_label }}">{{ form.text.label }}：</label>
            {{ form.text }}
            {{ form.text.errors }}
            <button type="submit" class="comment-btn">发表</button>
        </div>
    </div>    <!-- row -->
</form>

templates/comment/inclusions/_list.html
<h3>评论列表，共 <span>{{ comment_count }}</span> 条评论</h3>
<ul class="comment-list list-unstyled">
    {% for comment in comment_list %}
    <li class="comment-item">
        <span class="nickname">{{ comment.name }}</span>
        <time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
        <div class="text">
            {{ comment.text|linebreaks }}
        </div>
    </li>
    {% empty %}
    暂无评论
    {% endfor %}
</ul>

templates/comment/preview.html
{% extends 'base.html' %}
{% load comment_extras %}

{% block main %}
    {% show_comment_form post form %}
{% endblock main %}

templates/pure_pagination/pagination.html
<div class="text-center pagination" style="width: 100%">
    <ul>
    {% if page_obj.has_previous %}
        <li><a href="?{{ page_obj.previous_page_number.querystring }}"class="prev">&lsaquo;&lsaquo; </a></li>
    {% else %}
        <li><span class="disabled prev">&lsaquo;&lsaquo; </span></li>
    {% endif %}
    
    {% for page in page_obj.pages %}
        {% if page %}
            {% ifequal page page_obj.number %}
            <li class="current"><a href="#">{{ page }}</a></li>
            {% else %}
            <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
            {% endifequal %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    
    {% if page_obj.has_next %}
        <li><a href="?{{ page_obj.next_page_number.querystring }}" class="next"> &rsaquo;&rsaquo;</a></li>
    {% else %}
        <li><span class="disabled next"> &rsaquo;&rsaquo;</span></li>
    {% endif %}
    </ul>
</div>